version: "3.8"

services:

  tempo:
    image: grafana/tempo:0.7.0
    command: [ "--config.file=/etc/tempo-local.yaml" ]
    volumes:
      - ./etc/tempo-local.yaml:/etc/tempo-local.yaml
    ports:
      - "6831:6831/udp"
      - "9411:9411"
      - "3100:3100"
      - "55680:55680"
      - "14250:14250"

  tempo-query:
    image: grafana/tempo-query:0.7.0
    command: [ "--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
      - /etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui

  grafana-example:
    image: grafana-tempo-example:latest
    ports:
      - "8080:8080"

